# Generated by Django 5.2.6 on 2025-09-26 10:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_alter_topic_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='created_at',
        ),
        migrations.AddField(
            model_name='topic',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
